In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/marketing_campaign.csv', sep = ";")

In [6]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,84,...,7,0,0,0,0,0,0,3,11,1

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [9]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0

In [10]:
df.shape

(2240, 29)

In [11]:
df.ID.nunique()

2240

In [12]:
df.Education.unique()

array(['Graduation', 'PhD', 'Master', 'Basic', '2n Cycle'], dtype=object)

In [13]:
df.groupby("Education").agg(No_Customer = ("ID","count")).reset_index()

    Education  No_Customer
0    2n Cycle          203
1       Basic           54
2  Graduation         1127
3      Master          370
4         PhD          486

In [14]:
df.groupby("Marital_Status").agg(No_Customer = ("ID","count")).reset_index()

  Marital_Status  No_Customer
0         Absurd            2
1          Alone            3
2       Divorced          232
3        Married          864
4         Single          480
5       Together          580
6          Widow           77
7           YOLO            2

In [15]:
df['Children'] = df.Kidhome + df.Teenhome

In [16]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Children
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1,0
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0,2
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0,1
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0,1

In [17]:
df['Sum_Mnt_Prods'] = df.MntWines + df.MntFruits + df.MntMeatProducts +df.MntFishProducts + df.MntSweetProducts + df.MntSweetProducts

In [18]:
df[['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts',
       'MntSweetProducts', 'MntSweetProducts','Sum_Mnt_Prods']]

,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntSweetProducts,Sum_Mnt_Prods
0,635,88,546,172,88,88,1617
1,11,1,6,2,1,1,22
2,426,49,127,111,21,21,755
3,11,4,20,10,3,3,51
4,173,43,118,46,27,27,434
...,...,...,...,...,...,...,...
2235,709,43,182,42,118,118,1212
2236,406,0,30,0,0,0,436
2237,908,48,217,32,12,12,1229
2238,428,30,214,80,30,30,812
2239,84,3,61,2,1,1,152

In [19]:
df['Total_Purchases'] = df.NumDealsPurchases + df.NumWebPurchases + df.NumCatalogPurchases +df.NumStorePurchases + df.NumWebVisitsMonth

In [20]:
df[['NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
       'NumWebVisitsMonth','Total_Purchases']]

,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Total_Purchases
0,3,8,10,4,7,32
1,2,1,1,2,5,11
2,1,8,2,10,4,25
3,2,2,0,4,6,14
4,5,5,3,6,5,24
...,...,...,...,...,...,...
2235,2,9,3,4,5,23
2236,7,8,2,5,7,29
2237,1,2,3,13,6,25
2238,2,6,5,10,3,26
2239,3,3,1,4,7,18

In [21]:
df.columns[df.columns.str.contains("Accepted")]

Index(['AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2'],
      dtype='object')

In [22]:
df['Total_accepted'] = df[df.columns[df.columns.str.contains("Accepted")]].sum(axis = 1)

In [23]:
df[['ID','AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4',
       'AcceptedCmp5', 'Total_accepted','Recency']]

,ID,AcceptedCmp1,AcceptedCmp2,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,Total_accepted,Recency
0,5524,0,0,0,0,0,0,58
1,2174,0,0,0,0,0,0,38
2,4141,0,0,0,0,0,0,26
3,6182,0,0,0,0,0,0,26
4,5324,0,0,0,0,0,0,94
...,...,...,...,...,...,...,...,...
2235,10870,0,0,0,0,0,0,46
2236,4001,1,0,0,0,0,1,56
2237,7270,0,0,0,1,0,1,91
2238,8235,0,0,0,0,0,0,8
2239,9405,0,0,0,0,0,0,40

In [24]:
df['Dt_Customer'] = pd.to_datetime(df.Dt_Customer)

In [25]:
df['Dt_Customer'].dt.dayofweek

0       1
1       5
2       2
3       0
4       6
       ..
2235    3
2236    1
2237    5
2238    4
2239    0
Name: Dt_Customer, Length: 2240, dtype: int32

In [26]:
df['Dt_Customer'].dt.day_name()

0         Tuesday
1        Saturday
2       Wednesday
3          Monday
4          Sunday
          ...
2235     Thursday
2236      Tuesday
2237     Saturday
2238       Friday
2239       Monday
Name: Dt_Customer, Length: 2240, dtype: object

In [27]:
day_map = {
    0: 'Mon',
    1: 'Tue',
    2: 'Wed',
    3: 'Thu',
    4: 'Fri',
    5: 'Sat',
    6: 'Sun'
}

df['Day_Name_map'] = df['Dt_Customer'].dt.dayofweek.map(day_map)

In [28]:
df['Day_Name'] = df['Dt_Customer'].dt.day_name()

In [29]:
df[df.Education == 'PhD']

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Children,Sum_Mnt_Prods,Total_Purchases,Total_accepted,Day_Name_map,Day_Name
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0,1,434,24,0,Sun,Sunday
7,6177,1985,PhD,Married,33454.0,1,0,2013-05-08,32,76,10,56,3,1,23,2,4,0,4,8,0,0,0,0,0,0,3,11,0,1,147,18,0,Wed,Wednesday
8,4855,1974,PhD,Together,30351.0,1,0,2013-06-06,19,14,0,24,3,3,2,1,3,0,2,9,0,0,0,0,0,0,3,11,1,1,47,15,0,Thu,Thursday
9,5899,1950,PhD,Together,5648.0,1,1,2014-03-13,68,28,0,6,1,1,13,1,1,0,0,20,1,0,0,0,0,0,3,11,0,2,37,22,1,Thu,Thursday
15,2114,1946,PhD,Single,82800.0,0,0,2012-11-24,23,1006,22,115,59,68,45,1,7,6,12,3,0,0,1,1,0,0,3,11,1,0,1338,29,2,Sat,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,11133,1973,PhD,YOLO,48432.0,0,1,2012-10-18,3,322,3,50,4,3,42,5,7,1,6,8,0,0,0,0,0,0,3,11,1,1,385,27,0,Thu,Thursday
2217,9589,1948,PhD,Widow,82032.0,0,0,2014-04-05,54,332,194,377,149,125,57,0,4,6,7,1,0,0,0,0,0,0,3,11,0,0,1302,18,0,Sat,Saturday
2224,4286,1970,PhD,Single,57642.0,0,1,2014-01-09,24,580,6,58,8,0,27,3,7,6,6,4,1,0,0,0,0,0,3,11,0,1,652,26,1,Thu,Thursday
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,406,0,30,0,0,8,7,8,2,5,7,0,0,0,1,0,0,3,11,0,3,436,29,1,Tue,Tuesday
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,84,3,61,2,1,21,3,3,1,4,7,0,0,0,0,0,0,3,11,1,2,152,18,0,Mon,Monday

In [30]:
df['New_columns'] = df.Education.map({'PhD': 'Top', 'Basic': 'Basic'})

In [31]:
df.New_columns.value_counts().reset_index()

  New_columns  count
0         Top    486
1       Basic     54

In [32]:
df['Total_Purchases'] = df[df.columns[df.columns.str.contains("Purchase")]].sum(axis = 1)

In [33]:
df.to_csv('/content/marketing_campaign_cleaned.csv', index = False)

In [34]:
df.Total_Purchases.describe()

count    2240.000000
mean       35.040625
std        14.777451
min         0.000000
25%        22.000000
50%        35.000000
75%        46.000000
max        88.000000
Name: Total_Purchases, dtype: float64

In [35]:
def purchases(Total_Purchases):
  if Total_Purchases < 8:
    return ("Low")
  elif 8 <= Total_Purchases <= 15:
    return ("Medium")
  else:
    return ("High")

In [36]:
df['Purchase_Segment'] = df['Total_Purchases'].apply(lambda x: purchases(x))

In [37]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Children,Sum_Mnt_Prods,Total_Purchases,Total_accepted,Day_Name_map,Day_Name,New_columns,Purchase_Segment
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1,0,1617,57,0,Tue,Tuesday,NaN,High
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0,2,22,17,0,Sat,Saturday,NaN,High
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0,0,755,46,0,Wed,Wednesday,NaN,High
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0,1,51,22,0,Mon,Monday,NaN,High
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0,1,434,43,0,Sun,Sunday,Top,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,709,43,182,42,118,247,2,9,3,4,5,0,0,0,0,0,0,3,11,0,1,1212,41,0,Thu,Thursday,NaN,High
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,406,0,30,0,0,8,7,8,2,5,7,0,0,0,1,0,0,3,11,0,3,436,51,1,Tue,Tuesday,Top,High
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,908,48,217,32,12,24,1,2,3,13,6,0,1,0,0,0,0,3,11,0,0,1229,44,1,Sat,Saturday,NaN,High
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,428,30,214,80,30,61,2,6,5,10,3,0,0,0,0,0,0,3,11,0,1,812,49,0,Fri,Friday,NaN,High
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,84,3,61,2,1,21,3,3,1,4,7,0,0,0,0,0,0,3,11,1,2,152,29,0,Mon,Monday,Top,High

In [38]:
df.Sum_Mnt_Prods.describe()

count    2240.000000
mean      588.839286
std       602.144814
min         4.000000
25%        60.000000
50%       350.500000
75%      1014.000000
max      2639.000000
Name: Sum_Mnt_Prods, dtype: float64

In [39]:
def expense(Sum_Mnt_Prods):
  if Sum_Mnt_Prods < 60:
    return ("Low")
  elif 60 <= Sum_Mnt_Prods <= 350:
    return ("Medium")
  else:
    return ("High")

In [40]:
df['Mnt_Segment'] = df['Sum_Mnt_Prods'].apply(lambda x: expense(x))

In [41]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Children,Sum_Mnt_Prods,Total_Purchases,Total_accepted,Day_Name_map,Day_Name,New_columns,Purchase_Segment,Mnt_Segment
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1,0,1617,57,0,Tue,Tuesday,NaN,High,High
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0,2,22,17,0,Sat,Saturday,NaN,High,Low
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0,0,755,46,0,Wed,Wednesday,NaN,High,High
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0,1,51,22,0,Mon,Monday,NaN,High,Low
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0,1,434,43,0,Sun,Sunday,Top,High,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,709,43,182,42,118,247,2,9,3,4,5,0,0,0,0,0,0,3,11,0,1,1212,41,0,Thu,Thursday,NaN,High,High
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,406,0,30,0,0,8,7,8,2,5,7,0,0,0,1,0,0,3,11,0,3,436,51,1,Tue,Tuesday,Top,High,High
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,908,48,217,32,12,24,1,2,3,13,6,0,1,0,0,0,0,3,11,0,0,1229,44,1,Sat,Saturday,NaN,High,High
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,428,30,214,80,30,61,2,6,5,10,3,0,0,0,0,0,0,3,11,0,1,812,49,0,Fri,Friday,NaN,High,High
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,84,3,61,2,1,21,3,3,1,4,7,0,0,0,0,0,0,3,11,1,2,152,29,0,Mon,Monday,Top,High,Medium

In [52]:
customer_info = df[['ID','Year_Birth','Education','Marital_Status','Income','Kidhome','Teenhome','Children','Dt_Customer']]

In [53]:
customer_info

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Children,Dt_Customer
0,5524,1957,Graduation,Single,58138.0,0,0,0,2012-09-04
1,2174,1954,Graduation,Single,46344.0,1,1,2,2014-03-08
2,4141,1965,Graduation,Together,71613.0,0,0,0,2013-08-21
3,6182,1984,Graduation,Together,26646.0,1,0,1,2014-02-10
4,5324,1981,PhD,Married,58293.0,1,0,1,2014-01-19
...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,1,2013-06-13
2236,4001,1946,PhD,Together,64014.0,2,1,3,2014-06-10
2237,7270,1981,Graduation,Divorced,56981.0,0,0,0,2014-01-25
2238,8235,1956,Master,Together,69245.0,0,1,1,2014-01-24
2239,9405,1954,PhD,Married,52869.0,1,1,2,2012-10-15

In [44]:
sales = df[["ID",'MntWines','MntFruits','MntMeatProducts','MntFishProducts','MntSweetProducts','MntGoldProds','NumDealsPurchases','NumWebPurchases','NumCatalogPurchases','NumStorePurchases','NumWebVisitsMonth','Sum_Mnt_Prods','Total_Purchases','Purchase_Segment','Mnt_Segment','Z_CostContact','Z_Revenue']]

In [51]:
sales

,ID,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Sum_Mnt_Prods,Total_Purchases,Purchase_Segment,Mnt_Segment,Z_CostContact,Z_Revenue
0,5524,635,88,546,172,88,88,3,8,10,4,7,1617,57,High,High,3,11
1,2174,11,1,6,2,1,6,2,1,1,2,5,22,17,High,Low,3,11
2,4141,426,49,127,111,21,42,1,8,2,10,4,755,46,High,High,3,11
3,6182,11,4,20,10,3,5,2,2,0,4,6,51,22,High,Low,3,11
4,5324,173,43,118,46,27,15,5,5,3,6,5,434,43,High,High,3,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,709,43,182,42,118,247,2,9,3,4,5,1212,41,High,High,3,11
2236,4001,406,0,30,0,0,8,7,8,2,5,7,436,51,High,High,3,11
2237,7270,908,48,217,32,12,24,1,2,3,13,6,1229,44,High,High,3,11
2238,8235,428,30,214,80,30,61,2,6,5,10,3,812,49,High,High,3,11
2239,9405,84,3,61,2,1,21,3,3,1,4,7,152,29,High,Medium,3,11

In [46]:
experience = df[['ID','Recency','AcceptedCmp1','AcceptedCmp2','AcceptedCmp3','AcceptedCmp4','AcceptedCmp5','Total_accepted','Complain']]

In [47]:
experience

,ID,Recency,AcceptedCmp1,AcceptedCmp2,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,Total_accepted,Complain
0,5524,58,0,0,0,0,0,0,0
1,2174,38,0,0,0,0,0,0,0
2,4141,26,0,0,0,0,0,0,0
3,6182,26,0,0,0,0,0,0,0
4,5324,94,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
2235,10870,46,0,0,0,0,0,0,0
2236,4001,56,1,0,0,0,0,1,0
2237,7270,91,0,0,0,1,0,1,0
2238,8235,8,0,0,0,0,0,0,0
2239,9405,40,0,0,0,0,0,0,0

In [48]:
response = df[['ID','Response']]

In [49]:
response

         ID  Response
0      5524         1
1      2174         0
2      4141         0
3      6182         0
4      5324         0
...     ...       ...
2235  10870         0
2236   4001         0
2237   7270         0
2238   8235         0
2239   9405         1

[2240 rows x 2 columns]

In [54]:
experience.to_csv('/content/experience.csv', index = False, sep = ',')
sales.to_csv('/content/sales.csv', index = False, sep = ',')
response.to_csv('/content/response.csv', index = False, sep = ',')
customer_info.to_csv('/content/customer_info.csv', index = False, sep = ',')